### PR TITLE
removed used rss feed and fix miliseconds b0rked (aka same second posting)

### PR DESCRIPTION
**Pull request by chen-chan1**
this is some old feed from kolomya. when koko.php first runs it will make a new one.

### CODE REVIEW

**Comment by chen-chan1** [comment]
https://litter.catbox.moe/k5qsl7.mkv

**Comment by chen-chan1** [comment]
again idk why it put this in the same merge request but nao it should also fix teh b0rked time. i have a personal fork nao so when i add fixes it would not justshow  kotatsuba fork

**Comment by kaguy4** [comment]
I will merge this after checking it too

**Comment by chen-chan1** [comment]
can you please also change localhost to 127.0.0.1 in config.php
the test server i got was a vps from linode and running the Debian version as stated on here but the error message is really bad specifying it can not use localhost.

**Comment by chen-chan1** [comment]
https://stackoverflow.com/a/55886015

i prob should not have used a $time as a tmp var but it works the same. i don't think matters to much as it gets stored in the database truncated to a int.
i am changing this soon in a different fork to use this for file names https://www.php.net/manual/en/function.uniqid.php

**Pull request merged**
